apiVersion: externaldns.olm.openshift.io/v1alpha1
kind: ExternalDNS
metadata:
  name: sample-bluecat
spec:
  # DNS provider
  provider:
    type: BlueCat
    blueCat:
      configFile:
        # secret should be in the operator namespace
        name: bluecat-config
  domains:
  - filterType: Include
    matchType: Exact
    # domain of DNS zone must include the exact match of the given name
    name: myzonedomain.com
  source:
    type: Service
    service:
      # consider only those service types
      serviceType:
      - LoadBalancer
      - ClusterIP
    # consider source services only with these labels
    labelFilter:
      matchLabels:
        external-dns.mydomain.org/publish: "yes"
    # if hostname annotation is ignored
    # you can set a template for FQDN which will be created
    # note that this template will add the name of the service to FQDN
    # note also that the template has to match the zone's domain name
    fqdnTemplate:
    - "{{.Name}}.myzonedomain.com"
