apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: external-dns-operator
  name: external-dns-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns-operator
  namespace: external-dns-operator
  labels:
    name: external-dns-operator
spec:
  selector:
    matchLabels:
      name: external-dns-operator
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        name: external-dns-operator
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - name: external-dns-operator
        image: quay.io/openshift/origin-external-dns-operator:latest
        args:
        - --metrics-bind-address=127.0.0.1:8080
        - --operator-namespace=$(OPERATOR_NAMESPACE)
        - --operand-namespace=$(OPERATOR_NAMESPACE)
        - --externaldns-image=$(RELATED_IMAGE_EXTERNAL_DNS)
        - --trusted-ca-configmap=$(TRUSTED_CA_CONFIGMAP_NAME)
        - --leader-elect
        - --webhook-disable-http2
        terminationMessagePolicy: FallbackToLogsOnError
        env:
        - name: OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: RELATED_IMAGE_EXTERNAL_DNS
          # openshift/external-dns commit: 441588e482514db7722f5c793cf70348b68d952d
          # manifest link: https://quay.io/repository/external-dns-operator/external-dns/manifest/sha256:51e2acc81c804468932581379d674273fd2e62798be4e81c5c735bf0161590dd
          value: quay.io/external-dns-operator/external-dns:rhel9-rc1-224579246
        - name: TRUSTED_CA_CONFIGMAP_NAME
        securityContext:
          capabilities:
            drop:
            - "ALL"
          privileged: false
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          seccompProfile:
            type: "RuntimeDefault"
        resources:
          requests:
            cpu: 100m
            memory: 30Mi
      serviceAccountName: external-dns-operator
