apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: external-dns-operator
  name: openshift-external-dns-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns-operator
  namespace: openshift-external-dns-operator
  labels:
    name: external-dns-operator
spec:
  selector:
    matchLabels:
      name: external-dns-operator
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: external-dns-operator
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - name: external-dns-operator
        image: quay.io/openshift/origin-external-dns-operator:latest
        args:
        - --operator-namespace=$(OPERATOR_NAMESPACE)
        env:
        - name: OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        securityContext:
          allowPrivilegeEscalation: false
        resources:
          requests:
            cpu: 100m
            memory: 30Mi
      serviceAccountName: external-dns-operator
