apiVersion: v1
kind: Service
metadata:
  labels:
    name: external-dns-operator
  name: external-dns-operator-metrics-service
  namespace: openshift-external-dns-operator
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    name: external-dns-operator
