apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-dns-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns-operator
subjects:
- kind: ServiceAccount
  name: external-dns-operator
  namespace: openshift-external-dns-operator
