apiVersion: v1
kind: Service
metadata:
  labels:
    run: httpserver
  name: httpserver-ipv6
  namespace: publish-external-dns
spec:
  ipFamilies:
  - IPv6
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: httpserver
  type: ClusterIP
